# 网站基础配置
title: "神奇201-2"
description: "宿舍故事分享空间"
baseurl: ""
url: "https://hg6661.github.io"

# 主题设置
theme: null

# 插件
plugins:
  - jekyll-seo-tag

# 构建设置
markdown: kramdown
highlighter: rouge
permalink: pretty

# 包含目录
include:
  - _includes
  - _layouts

# 排除目录
exclude:
  - README.md
  - node_modules/
  - vendor/

# 社交链接
github_username: hg6661

# 其他设置
future: true
timezone: Asia/Shanghai
